name: mog_discord_bot
description: A Dart Discord Bot
version: 1.0.0
repository: https://github.com/newtox/Mog

environment:
  sdk: ^3.5.2

dependencies:
  collection: ^1.19.1
  dotenv: ^4.2.0
  http: ^1.3.0
  mysql1: ^0.20.0
  nyxx: ^6.6.0
  nyxx_commands: ^6.0.3
  nyxx_extensions: ^4.3.0
  nyxx_lavalink: ^4.0.0-dev.1
  path: ^1.9.1
  sqlite3: ^2.7.5
  yaml: ^3.1.3

dev_dependencies:
  lints: ^5.0.0
